# Change these first
owner: nevermined-io # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nevermined Website
    url: https://nevermined.ai
  - name: Nevermined App
    url: https://nevermined.app
  - name: Nevermined Docs
    url: https://nevermined.ai/docs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/nevermined-io/assets/refs/heads/main/images/app/dashboard-logo.svg
  name: Nevermined
  introTitle: "**Nevermined Status**"
  introMessage: Monitor the status of Nevermined applications
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
